M48
; DRILL file {KiCad 9.0.0} date 2025-05-27T07:28:03-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-27T07:28:03-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X35.55Y-27.575
X214.122Y-85.598
T2
X187.78Y-29.972
X188.034Y-41.402
M30
